### PR TITLE
Add basic support for OpenBGPd

### PR DESCRIPTION
**Pull request by ledeuns**
Add support for OpenBGPd and OpenBSD.
Limits : OpenBGPd has no support for AS regexp
TODO : add support for bgplgsh but auth/ssh.php needs some love as bgplgsh is not regular shell and exec() is not supported. Got to use write()

### CODE REVIEW

**Comment by respawner** [comment]
Thanks for this PR :)
About bgplgsh, could it be used as SSH subsystem?

**Comment by ledeuns** [comment]
In theory this would work but experiment shows it might not be usable.
There is no error management and hitting ^D makes bgplgsh enter an infinite loop :p

**Comment by respawner** [comment]
Maybe setting up a user dedicated to the looking glass with bgplgsh as default shell?

**Comment by ledeuns** [comment]
Yes, I think it is the best way. But as I stated, bgplgsh is not regular shell so exec() is not supported.

**Pull request merged**
