### PR TITLE
Adding support for vyatta

### PR DESCRIPTION
**Pull request by mikenowak**
This PR adds support for vyatta/vyos/edgerouter

### CODE REVIEW

**Comment by respawner** [comment]
This good to me. To be able to actually use this, you'll also need to modify routers/router.php to instanciate the object based on the configuration. So you'll need to add one or more router types (like vyos and/or vyatta).

A documentation to setup the VyOS/Vyatta router for the looking glass would be nice.

If you can do this in this pull request that would be nice. Otherwise I'll merge it and do it myself.

**Comment by mikenowak** [comment]
Sorry, forgot to git add router.php :)

Sure - I will add some documentation and squash with this commit

**Comment by mikenowak** [comment]
Some other things that I would need to put in the documentation

1) traceroute doesn't work properly at the moment - and this is because specifying a source ip (-s flag) requires root - I've logged a support case/enhancement request with Ubiquiti for this (822520).

2) The show bgp commands require that the the looking glass user has the admin privileges, and I am not sure if I like this very much - same case number (822520) with Ubiquity for enhancement.

**Comment by respawner** [comment]
Well this seems like good work to me. So it is mergeable IMHO.

If you can find some time to make a quick documentation and link the case number that you are mentioning (if it is opened to anyone) that would be great.

**Comment by mikenowak** [comment]
Yes, this is still on my todo list, so please wait a little bit longer.

**Comment by mikenowak** [comment]
Hi @respawner 

Unfortunately it looks like Ubiquiti took a different route and starting with EdgeOS [v1.9.7+hotfix.3](https://community.ubnt.com/t5/EdgeMAX-Updates-Blog/EdgeMAX-EdgeRouter-software-security-release-v1-9-7-hotfix-3/ba-p/2054117) shell access to the router is no longer possible for the operator users.

Here is a quote:
```
[User account] WARNING! Disabled shell access for operator user. From now on operator
user will have only WebUI access If operator user will try to access shell (via SSH or telnet)
then error message "This account is currently not available" will be displayed and access
will be denied. We decided to decrease operator user privileges for security reasons.
```
The only other way to implement this would be to use the admin account which I am hesitant to do so.

What is your take on this?

**Comment by respawner** [comment]
Maybe we can commit this with some documentation explaining this.
That's an issue indeed but users could use this at their own risks.

**Comment by mikenowak** [comment]
OK @respawner, I've added the docs -  let me know if you want me to include anything more.

**Pull request merged**
